# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: 'semantic'
    ports:
      - '3306:3306'
    volumes:
      - semantic-db:/var/lib/mysql
volumes:
  semantic-db:
